### ISSUE TITLE
Shared Properties

### ISSUE THREAD

**Issue by cyouh95** [Yahzmine/prj-rev-bwfs-dasmoto#3]
You could use comma-separated selectors to specify shared properties for multiple elements.

```css
.brushes, .frames, .paint {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

https://github.com/Yahzmine/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/Resources/css/index.css#L15-L37
